# Generated by Django 4.2.19 on 2025-02-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'holat',
            },
        ),
        migrations.CreateModel(
            name='MCHJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mchj',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'viloyat',
            },
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('mchj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mchj')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_name_or_full_name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MCHJUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mchj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mchj')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'mchj_user',
            },
        ),
        migrations.AddField(
            model_name='mchj',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viloyat'),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texnika_turi', models.CharField(max_length=255)),
                ('rusumi', models.CharField(default='kiritilmagan', max_length=255)),
                ('zavod_raqami', models.CharField(default='kiritilmagan', max_length=255)),
                ('davlat_raqami', models.CharField(default='kiritilmagan', max_length=255)),
                ('sana', models.CharField(max_length=255, null=True)),
                ('soni', models.IntegerField(default=0)),
                ('mchj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mchj')),
                ('texnik_holati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.holat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.type')),
            ],
            options={
                'db_table': 'instrument',
            },
        ),
    ]
