# Generated by Django 4.2.19 on 2025-02-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='davlat_raqami',
            field=models.CharField(blank=True, default='kiritilmagan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='mchj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mchj'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='rusumi',
            field=models.CharField(blank=True, default='kiritilmagan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='sana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='soni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='zavod_raqami',
            field=models.CharField(blank=True, default='kiritilmagan', max_length=255, null=True),
        ),
    ]
