# Generated by Django 4.2.19 on 2025-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
